---
# tasks file for motd
- name: Install epel release repository
  yum: 
    name: epel-release 
    state: latest
- name: Install figlet
  yum: 
    name: figlet
    state: latest
- name: write motd text
  shell:  figlet -f {{ motd_figlet_font }} {{ motd_text }} > /etc/motd
  when: motd_text != ""
- name: write motd with hostname
  shell:  figlet -f {{ motd_figlet_font }} {{ ansible_hostname }} > /etc/motd
  when: motd_text == ""  
- name: include print system info
  include_tasks: system-info.yml
  when: motd_print_system_info